version: '3'

services:
  lightbar:
    build: .
    links:
      - redis
    ports:
      - 5000:5000
    environment:
      REDIS_URL: redis://redis
      QUART_SECRET_KEY: "${QUART_SECRET_KEY}"
    networks:
      - lightbar

  redis:
    image: redis
    expose:
      - 6379
    networks:
      - lightbar

networks:
  lightbar:
