version: '3'

services:
  lightbar:
    build: .
    links:
      - redis
    ports:
      - 80:5000
    environment:
      REDIS_URL: redis://redis
    networks:
      - lightbar

  redis:
    image: redis
    expose:
      - 6379
    networks:
      - lightbar

networks:
  lightbar:
